services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./deploy:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: ${DB_NAME:-interior_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME:-interior_db}
      DB_USER: ${DB_APP_USER:-app_user}
      DB_PASSWORD: ${DB_APP_PASSWORD:-app_password}

volumes:
  postgres_data: